repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-json
      - id: detect-private-key

  # Cleanup generated files before Go hooks
  - repo: local
    hooks:
      - id: cleanup-generated
        name: Remove generated files
        entry: sh -c 'rm -f generated_tasks.go generated_tasks'
        language: system
        stages: [pre-commit]
        pass_filenames: false

  # Go-specific hooks
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.2
    hooks:
      - id: go-fmt
      - id: go-vet-mod
      - id: go-mod-tidy
      - id: golangci-lint-mod
