logging:
  level: info
  format: plain
  timestamps: true

execution_mode: parallel
executor: local
revert: true

# Host key checking configuration - just like in Ansible
# When true, SSH connections will check host keys (not fully implemented yet)
# When false, SSH connections will skip host key checking (insecure)
host_key_checking: false

temporal:
  address: ""
  task_queue: "SPAGE_DEFAULT_TASK_QUEUE"
  workflow_id_prefix: "spage-workflow"
  trigger: false

tags:
  tags: []
  skip_tags: []

facts:
  custom_fact: "example_value" 