---
- name: task 1
  shell:
    execute: "echo task 1"
    revert: echo 'reverting 1'
  register: hello_world

- name: task 2
  shell:
    execute: "echo task 2"
    revert: echo 'reverting 2'
  before: task 1

- name: task 3
  shell:
    execute: "echo 'previous task: {{ hello_world.stdout }}'"
    revert: echo 'reverting 3'
  after: "task 2"

- name: crash and burn
  shell:
    execute: exit 1
    revert: echo 'reverting failed task'
  after: "task 3"
