---
- name: generate graph
  shell:
    execute: curl -sSL https://mermaid-ascii.art/generate -d mermaid="graph LR\nA --> B" | tee /tmp/test.txt
    revert: rm /tmp/test.txt
  register: graph

- name: sleep a bit
  shell:
    execute: sleep 3

- name: show graph
  shell:
    execute: echo "{{ .graph.Stdout }}"
