---
- name: generate graph
  shell:
    execute: curl -sSL https://mermaid-ascii.art/generate -d mermaid="graph LR\nA --> B"
  register: graph

- name: write to file
  template:
    contents: "{{ .graph.Stdout }}"
    dest: /tmp/test.txt

