---
- name: task 1
  module: shell
  params:
    execute: echo 'hello world'
    revert: echo 'reverting'
  register: hello_world

- name: task 2
  module: shell
  params:
    execute: "echo task 2"
    revert: echo 'reverting 2'
  before: "task 1"

- name: task 3
  module: shell
  params:
    execute: "echo 'previous task: {{ hello_world.stdout }}'"
    revert: echo 'reverting 3'
  after: "task 2"

- name: crash and burn
  module: shell
  params:
    execute: exit 1
  after: "task 3"
