---
- name: basic packages
  pacman:
    name:
      - git
      - man-db
  run_as: root

- name: git clone yay
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
  register: yay_git

- name: test condition
  shell:
    execute: echo "{{ yay_git.dest }}"

# - name: install yay
#   shell:
#     execute: cd {{ .yay_git.Dest }} && makepkg -si --noconfirm
#   when: "{{ .yay_git.changed() }}"

# - name: install packages
#   yay:
#     name:
#       - nomad
#     state: present
#   after: install yay
