---
- name: task 1
  shell:
    execute: |
      echo task 1
      echo task 1 line 2
  register: hello_world

- name: task 2
  shell:
    execute: "echo 'previous task: {{ .hello_world.Stdout }}'"
    revert: echo 'reverting 3'

- name: place file
  template:
    src: example.tmpl
    dest: /tmp/test.txt

- name: crash
  shell:
    execute: exit 1
    revert: "echo 'Died after running {{ .Previous.Command }}'"
  after: place file
