---
- name: task 1
  shell:
    execute: |
      echo task 1
      echo task 1 line 2
  register: hello_world

- name: task 2
  shell:
    execute: "echo 'previous task: {{ .hello_world.Stdout }}'"
    revert: echo 'reverting 3'

#- name: crash and burn
#  shell:
#    execute: exit 1
#    revert: echo 'reverting failed task'
#  after: "task 3"
